meta_product_name: "SportsBnB"
meta_title: "SportsBnB"
meta_description: "Take your game to the next level. Game on."
meta_image: "https://res.cloudinary.com/dc4429yub/image/upload/v1582806599/dashboard/snowboarding_qmzrcl.jpg" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
